export const GET_PRODUCTS = 'GET_PRODUCTS'
export const CREATE_PRODUCT = 'CREATE_PRODUCT'
export const UPDATE_PRODUCT = 'UPDATE_PRODUCT'
export const DELETE_PRODUCT = 'DELETE_PRODUCT'

export const GET_PERMISSIONS = 'GET_PERMISSIONS'
export const UPDATE_PERMISSIONS = 'UPDATE_PERMISSIONS'
